version: '3.5'
services:

    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        container_name: ambassador_nginx

    app:
        build:
            context: ./
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: ambassador_app

    db:
        image: mysql:8
        restart: always
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ambassador_db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3309:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb_use_native_aio=0
        container_name: ambassador_db

    redis:
        image: "redis:alpine"
        command: redis-server --requirepass root
        ports:
            - "6379:6379"
        volumes:
            - ./redis/redis-data:/var/lib/redis
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_REPLICATION_MODE=master

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        external_links:
            - mailhog
        ports:
            - 1025:1025
            - 8025:8025
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro


volumes:
    db:

